### ISSUE TITLE
模型训练过程中出现loss为nan的情况

### ISSUE THREAD

**Issue by qiutzh** [EdisonChen0816/ner_toolkit#1]
模型使用的是19年百度三元组抽取的数据集，做了BIO的标注。但是在跑NER模型的时候，遇到了loss为nan的情况。
```shell
2021-01-05 15:21:22,065|INFO|epoch:0, batch: 1, current loss: 4.891431
2021-01-05 15:21:27,084|INFO|epoch:0, batch: 11, current loss: 2.107296
2021-01-05 15:21:32,181|INFO|epoch:0, batch: 21, current loss: 1.587927
2021-01-05 15:21:37,083|INFO|epoch:0, batch: 31, current loss: 1.623006
2021-01-05 15:21:42,095|INFO|epoch:0, batch: 41, current loss: 1.441218
2021-01-05 15:21:47,082|INFO|epoch:0, batch: 51, current loss: 1.633699
2021-01-05 15:21:52,022|INFO|epoch:0, batch: 61, current loss: 1.431985
2021-01-05 15:21:56,950|INFO|epoch:0, batch: 71, current loss: 1.522414
2021-01-05 15:22:01,940|INFO|epoch:0, batch: 81, current loss: 1.813167
2021-01-05 15:22:07,021|INFO|epoch:0, batch: 91, current loss: 1.624657
2021-01-05 15:22:12,263|INFO|epoch:0, batch: 101, current loss: 1.551381
2021-01-05 15:22:17,233|INFO|epoch:0, batch: 111, current loss: 1.678715
2021-01-05 15:22:22,373|INFO|epoch:0, batch: 121, current loss: 1.586228
2021-01-05 15:22:27,508|INFO|epoch:0, batch: 131, current loss: 1.618890
2021-01-05 15:22:32,430|INFO|epoch:0, batch: 141, current loss: 1.554004
2021-01-05 15:22:37,528|INFO|epoch:0, batch: 151, current loss: 1.410269
2021-01-05 15:22:42,554|INFO|epoch:0, batch: 161, current loss: 1.494321
2021-01-05 15:22:47,611|INFO|epoch:0, batch: 171, current loss: 1.544386
2021-01-05 15:22:52,782|INFO|epoch:0, batch: 181, current loss: 1.671600
2021-01-05 15:22:57,846|INFO|epoch:0, batch: 191, current loss: 2.201656
2021-01-05 15:23:03,076|INFO|epoch:0, batch: 201, current loss: 1.739955
2021-01-05 15:23:08,137|INFO|epoch:0, batch: 211, current loss: 1.327363
2021-01-05 15:23:13,193|INFO|epoch:0, batch: 221, current loss: 1.417326
2021-01-05 15:23:18,237|INFO|epoch:0, batch: 231, current loss: 1.573066
2021-01-05 15:23:23,198|INFO|epoch:0, batch: 241, current loss: 1.523618
2021-01-05 15:23:28,462|INFO|epoch:0, batch: 251, current loss: 1.457710
2021-01-05 15:23:33,487|INFO|epoch:0, batch: 261, current loss: 1.664142
2021-01-05 15:23:38,627|INFO|epoch:0, batch: 271, current loss: 1.414841
2021-01-05 15:23:43,770|INFO|epoch:0, batch: 281, current loss: 1.501700
2021-01-05 15:23:48,966|INFO|epoch:0, batch: 291, current loss: 1.478857
2021-01-05 15:23:54,023|INFO|epoch:0, batch: 301, current loss: 1.574372
2021-01-05 15:23:59,216|INFO|epoch:0, batch: 311, current loss: 1.566014
2021-01-05 15:24:04,513|INFO|epoch:0, batch: 321, current loss: 1.107716
2021-01-05 15:24:09,473|INFO|epoch:0, batch: 331, current loss: 1.363184
2021-01-05 15:24:14,568|INFO|epoch:0, batch: 341, current loss: 1.518904
2021-01-05 15:24:19,668|INFO|epoch:0, batch: 351, current loss: 1.654160
2021-01-05 15:24:24,833|INFO|epoch:0, batch: 361, current loss: 1.493039
2021-01-05 15:24:29,906|INFO|epoch:0, batch: 371, current loss: 1.776029
2021-01-05 15:24:34,950|INFO|epoch:0, batch: 381, current loss: 1.301449
2021-01-05 15:24:40,029|INFO|epoch:0, batch: 391, current loss: 1.443564
2021-01-05 15:24:45,134|INFO|epoch:0, batch: 401, current loss: 1.554070
2021-01-05 15:24:50,350|INFO|epoch:0, batch: 411, current loss: 1.879960
2021-01-05 15:24:55,421|INFO|epoch:0, batch: 421, current loss: 1.093695
2021-01-05 15:25:00,569|INFO|epoch:0, batch: 431, current loss: 1.537021
2021-01-05 15:25:05,618|INFO|epoch:0, batch: 441, current loss: 1.369968
2021-01-05 15:25:10,824|INFO|epoch:0, batch: 451, current loss: 1.495950
2021-01-05 15:25:16,124|INFO|epoch:0, batch: 461, current loss: 1.449695
2021-01-05 15:25:21,430|INFO|epoch:0, batch: 471, current loss: 1.284160
2021-01-05 15:25:26,492|INFO|epoch:0, batch: 481, current loss: 1.435600
2021-01-05 15:25:31,534|INFO|epoch:0, batch: 491, current loss: 1.286800
2021-01-05 15:25:36,746|INFO|epoch:0, batch: 501, current loss: 1.224918
2021-01-05 15:25:41,991|INFO|epoch:0, batch: 511, current loss: 1.609268
2021-01-05 15:25:47,095|INFO|epoch:0, batch: 521, current loss: 1.170993
2021-01-05 15:25:52,174|INFO|epoch:0, batch: 531, current loss: 1.377562
2021-01-05 15:25:57,186|INFO|epoch:0, batch: 541, current loss: 1.388859
2021-01-05 15:26:02,274|INFO|epoch:0, batch: 551, current loss: 1.436167
2021-01-05 15:26:07,352|INFO|epoch:0, batch: 561, current loss: 1.601248
2021-01-05 15:26:12,456|INFO|epoch:0, batch: 571, current loss: 1.464550
2021-01-05 15:26:17,678|INFO|epoch:0, batch: 581, current loss: 1.186732
2021-01-05 15:26:23,023|INFO|epoch:0, batch: 591, current loss: 1.158451
2021-01-05 15:26:28,045|INFO|epoch:0, batch: 601, current loss: 1.438261
2021-01-05 15:26:33,490|INFO|epoch:0, batch: 611, current loss: 1.427261
2021-01-05 15:26:38,592|INFO|epoch:0, batch: 621, current loss: 1.397371
2021-01-05 15:26:43,725|INFO|epoch:0, batch: 631, current loss: 1.213068
2021-01-05 15:26:48,729|INFO|epoch:0, batch: 641, current loss: 1.111083
2021-01-05 15:26:53,812|INFO|epoch:0, batch: 651, current loss: 1.340623
2021-01-05 15:26:58,860|INFO|epoch:0, batch: 661, current loss: 1.266470
2021-01-05 15:27:03,916|INFO|epoch:0, batch: 671, current loss: 1.138462
2021-01-05 15:27:08,970|INFO|epoch:0, batch: 681, current loss: 1.265563
2021-01-05 15:27:13,995|INFO|epoch:0, batch: 691, current loss: 1.297641
2021-01-05 15:27:19,063|INFO|epoch:0, batch: 701, current loss: 1.294289
2021-01-05 15:27:24,092|INFO|epoch:0, batch: 711, current loss: 1.590712
2021-01-05 15:27:29,106|INFO|epoch:0, batch: 721, current loss: 1.179820
2021-01-05 15:27:34,168|INFO|epoch:0, batch: 731, current loss: 1.137755
2021-01-05 15:27:39,245|INFO|epoch:0, batch: 741, current loss: 1.360206
2021-01-05 15:27:44,321|INFO|epoch:0, batch: 751, current loss: 1.123072
2021-01-05 15:27:49,457|INFO|epoch:0, batch: 761, current loss: 1.108911
2021-01-05 15:27:54,519|INFO|epoch:0, batch: 771, current loss: 1.344720
2021-01-05 15:27:59,706|INFO|epoch:0, batch: 781, current loss: 1.130805
2021-01-05 15:28:04,724|INFO|epoch:0, batch: 791, current loss: 1.403560
2021-01-05 15:28:09,779|INFO|epoch:0, batch: 801, current loss: 1.477908
2021-01-05 15:28:14,859|INFO|epoch:0, batch: 811, current loss: 1.044111
2021-01-05 15:28:19,836|INFO|epoch:0, batch: 821, current loss: 1.375230
2021-01-05 15:28:24,862|INFO|epoch:0, batch: 831, current loss: 0.979321
2021-01-05 15:28:29,918|INFO|epoch:0, batch: 841, current loss: 1.217908
2021-01-05 15:28:35,045|INFO|epoch:0, batch: 851, current loss: 0.984743
2021-01-05 15:28:40,168|INFO|epoch:0, batch: 861, current loss: 1.201761
2021-01-05 15:28:45,241|INFO|epoch:0, batch: 871, current loss: 1.274953
2021-01-05 15:28:50,171|INFO|epoch:0, batch: 881, current loss: 1.319326
2021-01-05 15:28:55,190|INFO|epoch:0, batch: 891, current loss: 1.251075
2021-01-05 15:29:00,288|INFO|epoch:0, batch: 901, current loss: 1.184837
2021-01-05 15:29:05,623|INFO|epoch:0, batch: 911, current loss: 1.150552
2021-01-05 15:29:10,689|INFO|epoch:0, batch: 921, current loss: 1.298113
2021-01-05 15:29:15,630|INFO|epoch:0, batch: 931, current loss: 1.129502
2021-01-05 15:29:20,596|INFO|epoch:0, batch: 941, current loss: 1.235778
2021-01-05 15:29:25,626|INFO|epoch:0, batch: 951, current loss: 1.189231
2021-01-05 15:29:30,585|INFO|epoch:0, batch: 961, current loss: 1.170776
2021-01-05 15:29:35,708|INFO|epoch:0, batch: 971, current loss: 0.944228
2021-01-05 15:29:40,818|INFO|epoch:0, batch: 981, current loss: 1.121288
2021-01-05 15:29:46,005|INFO|epoch:0, batch: 991, current loss: 0.907145
2021-01-05 15:29:51,077|INFO|epoch:0, batch: 1001, current loss: 0.961515
2021-01-05 15:29:56,243|INFO|epoch:0, batch: 1011, current loss: 1.660503
2021-01-05 15:30:01,409|INFO|epoch:0, batch: 1021, current loss: 1.016680
2021-01-05 15:30:06,550|INFO|epoch:0, batch: 1031, current loss: 1.101079
2021-01-05 15:30:11,628|INFO|epoch:0, batch: 1041, current loss: 0.935051
2021-01-05 15:30:16,634|INFO|epoch:0, batch: 1051, current loss: 1.080600
2021-01-05 15:30:21,706|INFO|epoch:0, batch: 1061, current loss: nan
2021-01-05 15:30:26,625|INFO|epoch:0, batch: 1071, current loss: nan
2021-01-05 15:30:31,684|INFO|epoch:0, batch: 1081, current loss: nan
2021-01-05 15:30:36,682|INFO|epoch:0, batch: 1091, current loss: nan
2021-01-05 15:30:41,590|INFO|epoch:0, batch: 1101, current loss: nan
2021-01-05 15:30:46,566|INFO|epoch:0, batch: 1111, current loss: nan
2021-01-05 15:30:51,459|INFO|epoch:0, batch: 1121, current loss: nan
2021-01-05 15:30:56,389|INFO|epoch:0, batch: 1131, current loss: nan
2021-01-05 15:31:01,361|INFO|epoch:0, batch: 1141, current loss: nan
2021-01-05 15:31:06,314|INFO|epoch:0, batch: 1151, current loss: nan
2021-01-05 15:31:11,260|INFO|epoch:0, batch: 1161, current loss: nan
^CTraceback (most recent call last):
```
后来，尝试对梯度做了clip，还是会出现了loss为nan的情况：
```shell
Caused by op 'VerifyFinite/CheckNumerics', defined at:
  File "/home/test/program/Train.py", line 176, in <module>
    result = model.train()
  File "/home/test/program/Train.py", line 92, in train
    result_dict = model.fit()
  File "/home/test/program/src/w2v_bilstm_crf.py", line 191, in fit
    clipped_gradients, norm = tf.clip_by_global_norm(gradients, 5.0)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py", line 271, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 44, in verify_tensor_all_finite
    return verify_tensor_all_finite_v2(t, msg, name)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 62, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 919, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
	 [[node VerifyFinite/CheckNumerics (defined at /home/test/program/src/w2v_bilstm_crf.py:142) ]]
```
另外，还尝试改过bert模型词汇量大小，改过学习率，改过batch_size，也都没起到作用 -_- 
参考：https://github.com/google-research/bert/issues/82

接着，多训练了几次，发现一个规律：模型总是在迭代第1061个batch时报nan的错。我开始怀疑是不是数据出问题了。但我检查过数据，实在想不出什么原因。您知道这是为啥么？

**Comment by EdisonChen0816** [comment]
调整一下学习率试试 把学习率调小试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EdisonChen0816/ner_toolkit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午4:20
收件人:&nbsp;"EdisonChen0816/ner_toolkit"<ner_toolkit@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EdisonChen0816/ner_toolkit] 模型训练过程中出现loss为nan的情况 (#1)





 
模型使用的是19年百度三元组抽取的数据集，做了BIO的标注。但是在跑NER模型的时候，遇到了loss为nan的情况。
 2021-01-05 15:21:22,065|INFO|epoch:0, batch: 1, current loss: 4.891431 2021-01-05 15:21:27,084|INFO|epoch:0, batch: 11, current loss: 2.107296 2021-01-05 15:21:32,181|INFO|epoch:0, batch: 21, current loss: 1.587927 2021-01-05 15:21:37,083|INFO|epoch:0, batch: 31, current loss: 1.623006 2021-01-05 15:21:42,095|INFO|epoch:0, batch: 41, current loss: 1.441218 2021-01-05 15:21:47,082|INFO|epoch:0, batch: 51, current loss: 1.633699 2021-01-05 15:21:52,022|INFO|epoch:0, batch: 61, current loss: 1.431985 2021-01-05 15:21:56,950|INFO|epoch:0, batch: 71, current loss: 1.522414 2021-01-05 15:22:01,940|INFO|epoch:0, batch: 81, current loss: 1.813167 2021-01-05 15:22:07,021|INFO|epoch:0, batch: 91, current loss: 1.624657 2021-01-05 15:22:12,263|INFO|epoch:0, batch: 101, current loss: 1.551381 2021-01-05 15:22:17,233|INFO|epoch:0, batch: 111, current loss: 1.678715 2021-01-05 15:22:22,373|INFO|epoch:0, batch: 121, current loss: 1.586228 2021-01-05 15:22:27,508|INFO|epoch:0, batch: 131, current loss: 1.618890 2021-01-05 15:22:32,430|INFO|epoch:0, batch: 141, current loss: 1.554004 2021-01-05 15:22:37,528|INFO|epoch:0, batch: 151, current loss: 1.410269 2021-01-05 15:22:42,554|INFO|epoch:0, batch: 161, current loss: 1.494321 2021-01-05 15:22:47,611|INFO|epoch:0, batch: 171, current loss: 1.544386 2021-01-05 15:22:52,782|INFO|epoch:0, batch: 181, current loss: 1.671600 2021-01-05 15:22:57,846|INFO|epoch:0, batch: 191, current loss: 2.201656 2021-01-05 15:23:03,076|INFO|epoch:0, batch: 201, current loss: 1.739955 2021-01-05 15:23:08,137|INFO|epoch:0, batch: 211, current loss: 1.327363 2021-01-05 15:23:13,193|INFO|epoch:0, batch: 221, current loss: 1.417326 2021-01-05 15:23:18,237|INFO|epoch:0, batch: 231, current loss: 1.573066 2021-01-05 15:23:23,198|INFO|epoch:0, batch: 241, current loss: 1.523618 2021-01-05 15:23:28,462|INFO|epoch:0, batch: 251, current loss: 1.457710 2021-01-05 15:23:33,487|INFO|epoch:0, batch: 261, current loss: 1.664142 2021-01-05 15:23:38,627|INFO|epoch:0, batch: 271, current loss: 1.414841 2021-01-05 15:23:43,770|INFO|epoch:0, batch: 281, current loss: 1.501700 2021-01-05 15:23:48,966|INFO|epoch:0, batch: 291, current loss: 1.478857 2021-01-05 15:23:54,023|INFO|epoch:0, batch: 301, current loss: 1.574372 2021-01-05 15:23:59,216|INFO|epoch:0, batch: 311, current loss: 1.566014 2021-01-05 15:24:04,513|INFO|epoch:0, batch: 321, current loss: 1.107716 2021-01-05 15:24:09,473|INFO|epoch:0, batch: 331, current loss: 1.363184 2021-01-05 15:24:14,568|INFO|epoch:0, batch: 341, current loss: 1.518904 2021-01-05 15:24:19,668|INFO|epoch:0, batch: 351, current loss: 1.654160 2021-01-05 15:24:24,833|INFO|epoch:0, batch: 361, current loss: 1.493039 2021-01-05 15:24:29,906|INFO|epoch:0, batch: 371, current loss: 1.776029 2021-01-05 15:24:34,950|INFO|epoch:0, batch: 381, current loss: 1.301449 2021-01-05 15:24:40,029|INFO|epoch:0, batch: 391, current loss: 1.443564 2021-01-05 15:24:45,134|INFO|epoch:0, batch: 401, current loss: 1.554070 2021-01-05 15:24:50,350|INFO|epoch:0, batch: 411, current loss: 1.879960 2021-01-05 15:24:55,421|INFO|epoch:0, batch: 421, current loss: 1.093695 2021-01-05 15:25:00,569|INFO|epoch:0, batch: 431, current loss: 1.537021 2021-01-05 15:25:05,618|INFO|epoch:0, batch: 441, current loss: 1.369968 2021-01-05 15:25:10,824|INFO|epoch:0, batch: 451, current loss: 1.495950 2021-01-05 15:25:16,124|INFO|epoch:0, batch: 461, current loss: 1.449695 2021-01-05 15:25:21,430|INFO|epoch:0, batch: 471, current loss: 1.284160 2021-01-05 15:25:26,492|INFO|epoch:0, batch: 481, current loss: 1.435600 2021-01-05 15:25:31,534|INFO|epoch:0, batch: 491, current loss: 1.286800 2021-01-05 15:25:36,746|INFO|epoch:0, batch: 501, current loss: 1.224918 2021-01-05 15:25:41,991|INFO|epoch:0, batch: 511, current loss: 1.609268 2021-01-05 15:25:47,095|INFO|epoch:0, batch: 521, current loss: 1.170993 2021-01-05 15:25:52,174|INFO|epoch:0, batch: 531, current loss: 1.377562 2021-01-05 15:25:57,186|INFO|epoch:0, batch: 541, current loss: 1.388859 2021-01-05 15:26:02,274|INFO|epoch:0, batch: 551, current loss: 1.436167 2021-01-05 15:26:07,352|INFO|epoch:0, batch: 561, current loss: 1.601248 2021-01-05 15:26:12,456|INFO|epoch:0, batch: 571, current loss: 1.464550 2021-01-05 15:26:17,678|INFO|epoch:0, batch: 581, current loss: 1.186732 2021-01-05 15:26:23,023|INFO|epoch:0, batch: 591, current loss: 1.158451 2021-01-05 15:26:28,045|INFO|epoch:0, batch: 601, current loss: 1.438261 2021-01-05 15:26:33,490|INFO|epoch:0, batch: 611, current loss: 1.427261 2021-01-05 15:26:38,592|INFO|epoch:0, batch: 621, current loss: 1.397371 2021-01-05 15:26:43,725|INFO|epoch:0, batch: 631, current loss: 1.213068 2021-01-05 15:26:48,729|INFO|epoch:0, batch: 641, current loss: 1.111083 2021-01-05 15:26:53,812|INFO|epoch:0, batch: 651, current loss: 1.340623 2021-01-05 15:26:58,860|INFO|epoch:0, batch: 661, current loss: 1.266470 2021-01-05 15:27:03,916|INFO|epoch:0, batch: 671, current loss: 1.138462 2021-01-05 15:27:08,970|INFO|epoch:0, batch: 681, current loss: 1.265563 2021-01-05 15:27:13,995|INFO|epoch:0, batch: 691, current loss: 1.297641 2021-01-05 15:27:19,063|INFO|epoch:0, batch: 701, current loss: 1.294289 2021-01-05 15:27:24,092|INFO|epoch:0, batch: 711, current loss: 1.590712 2021-01-05 15:27:29,106|INFO|epoch:0, batch: 721, current loss: 1.179820 2021-01-05 15:27:34,168|INFO|epoch:0, batch: 731, current loss: 1.137755 2021-01-05 15:27:39,245|INFO|epoch:0, batch: 741, current loss: 1.360206 2021-01-05 15:27:44,321|INFO|epoch:0, batch: 751, current loss: 1.123072 2021-01-05 15:27:49,457|INFO|epoch:0, batch: 761, current loss: 1.108911 2021-01-05 15:27:54,519|INFO|epoch:0, batch: 771, current loss: 1.344720 2021-01-05 15:27:59,706|INFO|epoch:0, batch: 781, current loss: 1.130805 2021-01-05 15:28:04,724|INFO|epoch:0, batch: 791, current loss: 1.403560 2021-01-05 15:28:09,779|INFO|epoch:0, batch: 801, current loss: 1.477908 2021-01-05 15:28:14,859|INFO|epoch:0, batch: 811, current loss: 1.044111 2021-01-05 15:28:19,836|INFO|epoch:0, batch: 821, current loss: 1.375230 2021-01-05 15:28:24,862|INFO|epoch:0, batch: 831, current loss: 0.979321 2021-01-05 15:28:29,918|INFO|epoch:0, batch: 841, current loss: 1.217908 2021-01-05 15:28:35,045|INFO|epoch:0, batch: 851, current loss: 0.984743 2021-01-05 15:28:40,168|INFO|epoch:0, batch: 861, current loss: 1.201761 2021-01-05 15:28:45,241|INFO|epoch:0, batch: 871, current loss: 1.274953 2021-01-05 15:28:50,171|INFO|epoch:0, batch: 881, current loss: 1.319326 2021-01-05 15:28:55,190|INFO|epoch:0, batch: 891, current loss: 1.251075 2021-01-05 15:29:00,288|INFO|epoch:0, batch: 901, current loss: 1.184837 2021-01-05 15:29:05,623|INFO|epoch:0, batch: 911, current loss: 1.150552 2021-01-05 15:29:10,689|INFO|epoch:0, batch: 921, current loss: 1.298113 2021-01-05 15:29:15,630|INFO|epoch:0, batch: 931, current loss: 1.129502 2021-01-05 15:29:20,596|INFO|epoch:0, batch: 941, current loss: 1.235778 2021-01-05 15:29:25,626|INFO|epoch:0, batch: 951, current loss: 1.189231 2021-01-05 15:29:30,585|INFO|epoch:0, batch: 961, current loss: 1.170776 2021-01-05 15:29:35,708|INFO|epoch:0, batch: 971, current loss: 0.944228 2021-01-05 15:29:40,818|INFO|epoch:0, batch: 981, current loss: 1.121288 2021-01-05 15:29:46,005|INFO|epoch:0, batch: 991, current loss: 0.907145 2021-01-05 15:29:51,077|INFO|epoch:0, batch: 1001, current loss: 0.961515 2021-01-05 15:29:56,243|INFO|epoch:0, batch: 1011, current loss: 1.660503 2021-01-05 15:30:01,409|INFO|epoch:0, batch: 1021, current loss: 1.016680 2021-01-05 15:30:06,550|INFO|epoch:0, batch: 1031, current loss: 1.101079 2021-01-05 15:30:11,628|INFO|epoch:0, batch: 1041, current loss: 0.935051 2021-01-05 15:30:16,634|INFO|epoch:0, batch: 1051, current loss: 1.080600 2021-01-05 15:30:21,706|INFO|epoch:0, batch: 1061, current loss: nan 2021-01-05 15:30:26,625|INFO|epoch:0, batch: 1071, current loss: nan 2021-01-05 15:30:31,684|INFO|epoch:0, batch: 1081, current loss: nan 2021-01-05 15:30:36,682|INFO|epoch:0, batch: 1091, current loss: nan 2021-01-05 15:30:41,590|INFO|epoch:0, batch: 1101, current loss: nan 2021-01-05 15:30:46,566|INFO|epoch:0, batch: 1111, current loss: nan 2021-01-05 15:30:51,459|INFO|epoch:0, batch: 1121, current loss: nan 2021-01-05 15:30:56,389|INFO|epoch:0, batch: 1131, current loss: nan 2021-01-05 15:31:01,361|INFO|epoch:0, batch: 1141, current loss: nan 2021-01-05 15:31:06,314|INFO|epoch:0, batch: 1151, current loss: nan 2021-01-05 15:31:11,260|INFO|epoch:0, batch: 1161, current loss: nan ^CTraceback (most recent call last):
 
后来，尝试对梯度做了clip，还是会出现了loss为nan的情况：
 Caused by op 'VerifyFinite/CheckNumerics', defined at:   File "/home/test/program/Train.py", line 176, in <module&gt;     result = model.train()   File "/home/test/program/Train.py", line 92, in train     result_dict = model.fit()   File "/home/test/program/src/w2v_bilstm_crf.py", line 191, in fit     clipped_gradients, norm = tf.clip_by_global_norm(gradients, 5.0)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py", line 271, in clip_by_global_norm     "Found Inf or NaN global norm.")   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 44, in verify_tensor_all_finite     return verify_tensor_all_finite_v2(t, msg, name)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 62, in verify_tensor_all_finite_v2     verify_input = array_ops.check_numerics(x, message=message)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 919, in check_numerics     "CheckNumerics", tensor=tensor, message=message, name=name)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper     op_def=op_def)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func     return func(*args, **kwargs)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op     op_def=op_def)   File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__     self._traceback = tf_stack.extract_stack() InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values 	 [[node VerifyFinite/CheckNumerics (defined at /home/test/program/src/w2v_bilstm_crf.py:142) ]]
 
另外，还尝试改过bert模型词汇量大小，也没起到作用 -_-
 参考：google-research/bert#82
 
接着，多训练了几次，发现一个规律：模型总是在迭代第1061个batch时报nan的错。我开始怀疑是不是数据出问题了。但我检查过数据，实在想不出什么原因。您知道这是为啥么？

**Comment by qiutzh** [comment]
@EdisonChen0816 回复也太快了吧，^_^。我设置过rate为1e-4, 5e-5,都在第1061个batch出错了。

**Comment by qiutzh** [comment]
@EdisonChen0816 我是觉得和数据应该有点关系。因为我前段时间在一个特定任务的小批量数据集上跑过ner模型，没有出现异常。百度的数据集相对来说多了很多。

**Comment by EdisonChen0816** [comment]
调整rate或者batch 如果这招不行 那就看数据向量中有没有inf&nbsp;
可以把1061批数据向量print出来
如果没有inf 那我也不清楚了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EdisonChen0816/ner_toolkit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午4:28
收件人:&nbsp;"EdisonChen0816/ner_toolkit"<ner_toolkit@noreply.github.com&gt;;
抄送:&nbsp;"Edison"<moon0816@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [EdisonChen0816/ner_toolkit] 模型训练过程中出现loss为nan的情况 (#1)





 
@EdisonChen0816 回复也太快了吧，^_^。我设置过rate为1e-4, 5e-5,都在第1061个batch出错了。

**Comment by qiutzh** [comment]
@EdisonChen0816 好的，我再好好检查下数据，谢谢了

**Comment by qiutzh** [comment]
@EdisonChen0816 您知道怎么在bert默认模型（chinese_L-12_H-768_A-12）的基础上，添加一些新的词汇进去后，该调整哪些内容吗？下面的附件1在原始bert模型的vocab.txt上新增了2000多个百度数据集里面的生僻字，一共有23560行（原始的是21128行）。在这里新增完后，我把bert_config.json里面的vocab_size也做了同步处理，但是训练模型时，存在以下错误：

```shell
Instructions for updating:
Use tf.cast instead.
/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "/home/test/program/Train.py", line 202, in <module>
    result = model.train()
  File "/home/test/program/Train.py", line 91, in train
    result_dict = model.fit()
  File "/home/test/program/src/bert_crf.py", line 160, in fit
    tf.train.init_from_checkpoint(init_checkpoint, assignment_map)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 190, in init_from_checkpoint
    _init_from_checkpoint, args=(ckpt_dir_or_file, assignment_map))
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1516, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1524, in _merge_call
    return merge_fn(self._distribution_strategy, *args, **kwargs)
  File "/opt/anaconda3/envs/ml-py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 229, in _init_from_checkpoint
    tensor_name_in_ckpt, str(variable_map[tensor_name_in_ckpt])
ValueError: Shape of variable bert/embeddings/word_embeddings:0 ((23560, 768)) doesn't match with shape of tensor bert/embeddings/word_embeddings ([21128, 768]) from checkpoint reader.
```

似乎原始bert模型里面只存储了那21128个词，不太明白错在哪里了，该怎么修改。附件2中是调试模型时的一些记录，您可以参考下。大佬有空帮我看下吧~
1. [train_bug_nan.txt](https://github.com/EdisonChen0816/ner_toolkit/files/5854067/train_bug_nan.txt)
2. [vocab.txt](https://github.com/EdisonChen0816/ner_toolkit/files/5854081/vocab.txt)

**Comment by qiutzh** [comment]
@EdisonChen0816 经验证，直接把那些带生僻字的sentence过滤掉，不起作用，训练到第5000多个batch时还是出现nan，用的是默认vocab.txt-_-
